plugins {
    id("com.android.application")
    id("kotlin-android")
}

android {
    namespace 'com.example.assignment6'
    compileSdk 34


    defaultConfig {
        applicationId "com.example.assignment6"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding = true


    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies { // App Level build.gradle.kts



    implementation("com.google.android.material:material:1.9.0")


    //New dependencies


    implementation(libs.androidx.navigation.fragment.ktx)


    implementation(libs.androidx.navigation.ui.ktx)


    implementation("com.google.code.gson:gson:2.10.1")


    implementation(libs.firebase.crashlytics.buildtools)


}